#spring.datasource.url=jdbc:mysql://localhost:3306/betamovie
#spring.datasource.username=root
#spring.datasource.password=151611
#spring.jpa.hibernate.ddl-auto=update
#
#  ## Hibernate Properties
#  # The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
#


server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/betamovie"
    username: root
    password: 151611

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
